
version: '3'

services:
  web:
    build: .
    command: gunicorn panoramic_trekking_app.wsgi:application --bind 0.0.0.0:8000
    container_name: service
    volumes:
      - .:/service
#    expose:
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=docker

#  nginx:
#    build: ./nginx
#    ports:
#      - 1337:80
#    depends_on:
#      - web

volumes:
  postgres_data:
 
